package com.gallapillo.weather.z_utils

val COUNTRIES = arrayOf(
    "Tokyo",
    "Jakarta",
    "Delhi",
    "Mumbai",
    "Manila",
    "Shanghai",
    "São Paulo",
    "Seoul",
    "Mexico City",
    "Guangzhou",
    "Beijing",
    "Cairo",
    "New York",
    "Kolkāta",
    "Moscow",
    "Bangkok",
    "Buenos Aires",
    "Shenzhen",
    "Dhaka",
    "Lagos",
    "Istanbul",
    "Ōsaka",
    "Karachi",
    "Bangalore",
    "Tehran",
    "Kinshasa",
    "Ho Chi Minh City",
    "Los Angeles",
    "Rio de Janeiro",
    "Nanyang",
    "Baoding",
    "Chennai",
    "Chengdu",
    "Lahore",
    "Paris",
    "London",
    "Linyi",
    "Tianjin",
    "Shijiazhuang",
    "Zhoukou",
    "Lima",
    "Hyderābād",
    "Handan",
    "Bogotá",
    "Weifang",
    "Nagoya",
    "Wuhan",
    "Heze",
    "Novosibirsk",
    "Java",
    "Ganzhou",
    "Tongshan",
    "Chicago",
    "Luanda",
    "Changsha",
    "Fuyang",
    "Kuala Lumpur",
    "Jining",
    "Dongguan",
    "Jinan",
    "Foshan",
    "Hanoi",
    "Pune",
    "Chongqing",
    "Changchun",
    "Zhumadian",
    "Ningbo",
    "Cangzhou",
    "Nanjing",
    "Hefei",
    "Ahmedabad",
    "Hong Kong",
    "Zhanjiang",
    "Shaoyang",
    "Hengyang",
    "Khartoum",
    "Nantong",
    "Yancheng",
    "Nanning",
    "Xi’an",
    "Shenyang",
    "Tangshan",
    "Santiago",
    "Zhengzhou",
    "Shangqiu",
    "Yantai",
    "Riyadh",
    "Dar es Salaam",
    "Xinyang",
    "Shangrao",
    "Luoyang",
    "Bijie",
    "Quanzhou",
    "Hangzhou",
    "Miami",
    "Huanggang",
    "Maoming",
    "Kunming",
    "Nanchong",
    "Petropavlovsk Kamchatsky",
    "Toronto",
    "Brest"
)